/*********************************************************************
 *
 * This file is autogenerated by /u/profi/aali/sfsRoot/UCESB/lu_common/make_acc_auto_def.sh
 *
 * Editing is useless.
 *
 *********************************************************************
 *
 * Input file:    /u/profi/aali/sfsRoot/UCESB/acc_def/has_pthread_getname_np.h
 * Basename:      HAS_PTHREAD_GETNAME_NP
 * Compiler:      g++
 * Compiler args: -I. -DUNPACKERNAME=s115 -DUNPACKER_IS_s115 -I/u/profi/aali/sfsRoot/UCESB/file_input -I/u/profi/aali/sfsRoot/UCESB/file_input/lmd_struct -I/u/profi/aali/sfsRoot/UCESB/threading -I/u/profi/aali/sfsRoot/UCESB/lu_common -I/u/profi/aali/sfsRoot/UCESB/acc_def -ansi -Wall -W -Wno-unused-function -Wno-unused-label -Wno-unused-parameter -Wwrite-strings -Wconversion -g -D_LARGEFILE_SOURCE -D_FILE_OFFSET_BITS=64 -D__STDC_LIMIT_MACROS -DHAVE_TEE -Igen_s115 -DGENDIR="gen_s115" -DUSE_EXT_WRITER= -DUSING_EXT_WRITER= -DEXT_WRITER_PREFIX="../../../../UCESB/hbook/" -I/u/profi/aali/sfsRoot/UCESB/hbook -DUSE_CURSES=1 -I/u/profi/aali/sfsRoot/UCESB/watcher -D_DEFAULT_SOURCE -D_XOPEN_SOURCE=600 -DCONTROL_INCLUDE -Wfatal-errors -DHAVE_THREAD_LOCAL_STORAGE -pthread -DUSE_PTHREAD=1 -DHAVE_PTHREAD -DUSE_LMD_INPUT=1 -DUSE_LMD_OUTPUT_TCP -I/u/profi/aali/sfsRoot/UCESB/mapcalib
 *
 ********************************************************************/

#ifndef __AUTO_DEF__HAS_PTHREAD_GETNAME_NP_HH__
#define __AUTO_DEF__HAS_PTHREAD_GETNAME_NP_HH__

/*
 * Option: pthread_h
 * Option: notavail
 */
/*
 * -DACC_DEF_HAS_PTHREAD_GETNAME_NP_pthread_h



 * --> exit 0 (len 0)
 */
/*
 * -DACC_DEF_HAS_PTHREAD_GETNAME_NP_notavail



 * --> exit 0 (len 0)
 */

/********************************************************************/

#define ACC_DEF_HAS_PTHREAD_GETNAME_NP_pthread_h 1

/********************************************************************/

#endif/*__AUTO_DEF__HAS_PTHREAD_GETNAME_NP_HH__*/
